spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  mvc:
    pathmatch:
      matching-strategy: ${SPRING_MVC_MATCHING_STRATEGY}
  # Database
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    show-sql: ${SPRING_JPA_SHOW_SQL}
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM}
    generate-ddl: ${SPRING_JPA_GENERATE_DDL}